apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-deployment-alert-webhook
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: deployment-alerting
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-deployment-alert-webhook
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-postgres
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: postgres
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-postgres
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-stytch
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: identity
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-stytch
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-calendar-encryption
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: calendar-import
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-calendar-encryption
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-family-data-encryption
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: family-data-protection
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-family-data-encryption
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-google-places
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: location-search
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-google-places
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-resend-invitations
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: invitation-email
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-resend-invitations
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-apns
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: push-notifications
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-apns
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-observability
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: observability
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-observability
